name: I2::Release::Publish

on:
  push:
    branches: [iroha2-stable, iroha2-lts]

env:
  CARGO_TERM_COLOR: always
  TARGET_DIR: /iroha/target/x86_64-unknown-linux-musl/deploy

jobs:
  registry:
    runs-on: ubuntu-latest
    container:
      image: hyperledger/i2-ci:dev
    steps:
      - uses: actions/checkout@v3
      - name: Get tag from branch name
        run: |
          BRANCH=${{ github.ref_name }}
          PREFIX='iroha2-'
          TAG=${BRANCH#$PREFIX}
          echo "TAG=$TAG" >>$GITHUB_ENV
      - name: Iroha2 build
        run: mold --run cargo build --profile deploy --target x86_64-unknown-linux-musl --features vendored
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Soramitsu Harbor
        uses: docker/login-action@v2
        with:
          registry: docker.soramitsu.co.jp
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Build and push iroha2 image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            hyperledger/iroha2:${{ env.TAG }}
            docker.soramitsu.co.jp/iroha2/iroha2:${{ env.TAG }}-${{ github.sha }}
          labels: commit=${{ github.sha }}
          build-args: TAG=${{ env.TAG }}
          file: Dockerfile
          # This context specification is required
          context: .
      - name: Upload iroha2 binaries artifacts
        uses: actions/upload-artifact@v3
        with:
          name: iroha2-${{ env.TAG }}-artifacts
          path: |
            ${{ env.TARGET_DIR}}/iroha
            ${{ env.TARGET_DIR}}/iroha_client_cli
            ${{ env.TARGET_DIR}}/kagami

  load-rs:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag from branch name
        run: |
          BRANCH=${{ github.ref_name }}
          PREFIX='iroha2-'
          TAG=${BRANCH#$PREFIX}
          echo "TAG=$TAG" >>$GITHUB_ENV
      - name: Build and push docker image (load-rs:stable/lts)
        run: |
          sleep 10s
          echo "wait to finish other workflow"
      - uses: convictional/trigger-workflow-and-wait@v1.6.2
        with:
          owner: soramitsu
          repo: iroha2-longevity-load-rs
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: load-rs-push-from-${{ env.TAG }}.yaml
          ref: iroha2-${{ env.TAG }}
