name: I2::Release::Publish

on:
  push:
    tags:
      - 'v2*'

env:
  CARGO_TERM_COLOR: always
  DOCKER_COMPOSE_PATH: configs/swarm

jobs:
  registry:
    runs-on: ubuntu-latest
    container:
      image: hyperledger/iroha2-ci:nightly-2024-04-18
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Get the release tag
        run: |
          RELEASE_VERSION=${{ github.ref_name }}
          PREFIX='v'
          TAG=${RELEASE_VERSION#$PREFIX}
          echo "TAG=$TAG" >>$GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Soramitsu Harbor
        uses: docker/login-action@v3
        with:
          registry: docker.soramitsu.co.jp
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Build and push iroha2 image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            hyperledger/iroha:${{ env.TAG }}
            docker.soramitsu.co.jp/iroha2/iroha:${{ env.TAG }}
          file: Dockerfile
          # This context specification is required
          context: .
          labels: commit=${{ github.sha }}
