name: I2::Dev::Publish

on:
  push:
    branches: [iroha2-dev]

env:
  CARGO_TERM_COLOR: always

# Note jobs in this workflow are run on `push` meaning that there's
# no point in burning our AWS self-hosted runners' time. Hence
# `ubuntu-latest` and not `[self-hosted, Linux]`.
jobs:
  ci-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check changed files
        uses: jitterbit/get-changed-files@v1
        id: changed_config
      - name: Build and push iroha2-base:dev image
        uses: docker/build-push-action@v3
        if: contains(steps.changed_config.outputs.added_modified, 'Dockerfile.base')
        with:
          push: true
          tags: hyperledger/iroha2-base:dev
          labels: commit=${{ github.sha }}
          file: Dockerfile.base
      - name: Build and push iroha2-planner:dev image
        uses: docker/build-push-action@v3
        if: contains(steps.changed_config.outputs.added_modified, 'Cargo.lock')
        with:
          push: true
          tags: hyperledger/iroha2-planner:dev
          labels: commit=${{ github.sha }}
          file: Dockerfile.planner
          context: .

  dockerhub:
    runs-on: ubuntu-latest
    container:
      image: hyperledger/iroha2-planner:dev
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push iroha2:dev image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: hyperledger/iroha2:dev
          labels: commit=${{ github.sha }}
          build-args: TAG=dev
          file: Dockerfile
          # This context specification is required!
          context: .

  load-rs:
    runs-on: ubuntu-latest
    container:
      image: hyperledger/iroha2-planner:dev
    steps:
      - name: Build and push docker image (load-rs:dev)
        run: |
          sleep 10s
          echo "wait to other workflow"
      - uses: convictional/trigger-workflow-and-wait@v1.6.2
        with:
          owner: soramitsu
          repo: iroha2-longevity-load-rs
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: load-rs-push-from-dev.yaml
          ref: iroha2-dev

      - name: Build and push docker image (load-rs:dev)
        run: |
          sleep 10s
          echo "wait to other workflow"
      - uses: convictional/trigger-workflow-and-wait@v1.6.2
        with:
          owner: soramitsu
          repo: iroha2-longevity-load-rs
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: load-rs-push-from-dev.yaml
          ref: iroha2-dev

  archive_binaries_and_schema:
    runs-on: ubuntu-latest
    container:
      image: hyperledger/iroha2-planner:dev
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: mold --run cargo build --release --verbose
      - name: Archive iroha
        uses: actions/upload-artifact@v3
        with:
          name: cargo-build-release
          path: target/release/iroha
      - name: Archive iroha_client_cli
        uses: actions/upload-artifact@v3
        with:
          name: cargo-client-cli-build-release
          path: target/release/iroha_client_cli
      - name: Archive kagami
        uses: actions/upload-artifact@v3
        with:
          name: cargo-crypto-cli-build-release
          path: target/release/kagami
      - name: Generate schema
        run: |
          mkdir -p target/schema
          cargo run --bin kagami -- schema >target/schema/schema.json
      - name: Archive schema
        uses: actions/upload-artifact@v3
        with:
          name: schema
          path: target/schema

  telemetry:
    # FIXME #2646
    if: false
    runs-on: ubuntu-latest
    container:
      image: hyperledger/iroha2-planner:dev
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run debug tests and save telemetry
        env:
          TELEMETRY_FILE: ../target/telemetry/debug.json.lz4
        run: |
          mkdir -p target/telemetry
          mold --run cargo test -p iroha_client --all-features -- unstable_network || true
      - name: Run release tests and save telemetry
        env:
          TELEMETRY_FILE: ../target/telemetry/release.json.lz4
        run: mold --run cargo test -p iroha_client --all-features --release -- unstable_network || true
      - name: Install script dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends lz4 jq
      - name: Print debug telemetry info
        run: |
          ./scripts/analyze_telemetry.sh target/telemetry/debug.json.lz4 >target/telemetry/debug.md
      - name: Print release telemetry info
        run: ./scripts/analyze_telemetry.sh target/telemetry/release.json.lz4 >target/telemetry/release.md
      - name: Print debug telemetry info
        run: |
          echo '## Debug build'
          cat target/telemetry/debug.md
      - name: Print release telemetry info
        run: |
          echo '## Release build'
          cat target/telemetry/release.md
      - name: Create telemetry comment
        uses: actions-ecosystem/action-create-comment@v1
        with:
          body: |
            \# Telemetry info
            \## Debug build
            ${{ steps.debug-telemetry.outputs.body }}
            \## Release build
            ${{ steps.release-telemetry.outputs.body }}
          github_token: ${{ secrets.github_token }}
        continue-on-error: true
      - name: Archive telemetry
        uses: actions/upload-artifact@v3
        with:
          name: telemetry
          path: target/telemetry
