name: I2::Dev::CodeQuality

on:
  workflow_run:
    workflows: ["I2::Dev::Tests"]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  sonarqube-defectdojo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download clippy and lcov artifact reports
        uses: actions/download-artifact@v4
        with:
            path: lints
            run-id: ${{ github.event.workflow_run.id }}
            github-token: ${{ secrets.G_ACCESS_TOKEN }}
      - name: Show artifact
        run: |
          ls -la lints
